Kto 955 arkistoitujen filtterointi
Opetushallitus/kouta-ui pull request #217
Opened 2020-11-06 08:30 UTC by vesaruu

Bäkkärin /list apien kutsut laitettu filtteröimään arkistoidut pois Laitettu käännös dropdownien tila-tiedolle.

2020-11-09 16:13 UTC, pretseli requested changes

2020-11-10 10:24 UTC, vesaruu commented on src/main/app/src/constants.ts
> +}
Laitoin tuon enumiksi koska sillä oli mukavampi tyypittää funktion parametri. Halusin että tälle funktiolle pystyy antamaan ainoastaan jonkun noista kolmesta arvosta. Minä olen kokenut enumin ihan käteväksi jos on kyse muutamasta  kovakoodatusta arvosta. Yksi vaihtoehto olisi myös käyttää typescriptin union typeä tällaisissa tilanteissa.

2020-11-10 10:37 UTC, vesaruu commented on src/main/app/src/pages/HomePage/HakukohteetSection/LiitoksetModal.tsx
Hyvä huomio, en itse aiemmin juurikaan käyttänyt hookeja joten vähän vielä epävarmaa miten näitä kannattaa käyttää. Pitää jossain vaiheessa lukea hookien dokumentaatio läpi.

2020-11-10 10:45 UTC, vesaruu commented on src/main/app/src/urls.ts
> -  'kouta-backend.hakukohde-list': `${koutaBackendDevUrl}/hakukohde/list`,
Argh minulla oli jäänyt idean grepissä päälle asetus että hakee ainoastaan main/app/src kansion alta. Hyvä kun huomasit.

2020-11-10 13:48 UTC, vesaruu commented on src/main/app/src/components/PohjaValintaSection.tsx
Tehty muutokset

2020-11-11 07:40 UTC, pretseli approved these changes

2020-11-11 08:06 UTC, merged