Kto 1090
Opetushallitus/kouta-ui pull request #284
Opened 2021-04-08 12:47 UTC by AnttiSarjanoja

2021-04-09 09:02 UTC, pretseli requested changes

2021-04-09 09:10 UTC, AnttiSarjanoja commented on src/main/app/src/components/StyledSectionHTML.tsx
> +    noMargin &&
Se ylikirjoittaa lasten marginit (& *), eli käytännössä sen parsitun HTML:n. Voisin nimetä paremmin. HTML editori tunkee sisällön <p> sisään jolloin se teksti kaivaa jostain globaalista tyylistä että <p> tarvii isot marginit ympärilleen.

2021-04-09 09:14 UTC, AnttiSarjanoja commented on src/main/app/cypress/data/hakukohde.ts
> +        id: 'undefined',
Jees, pitää tunkata myös valintaperusteen valintakokeille sama id

2021-04-16 07:50 UTC, pretseli commented on src/main/app/src/components/TilaisuudetFields.tsx
> +        css={{ backgroundColor: 'white' }}
Tähän on vielä tainnut jääny vaihtamatta tuo `backgroundColor`.

2021-04-16 08:00 UTC, AnttiSarjanoja commented on src/main/app/src/components/TilaisuudetFields.tsx
> +        css={{ backgroundColor: 'white' }}
Tolla napilla ei ollut taustaväriä enkä halunnut että se on harmaalla pohjalla harmaa -> kovakoodasin valkosen.

Siinä varmaan itse asiassa on paras pitää aina valkonen tausta

2021-04-19 07:47 UTC, merged