Kto 1274 tuva komo
Opetushallitus/kouta-ui pull request #331
Opened 2021-08-09 13:33 UTC by heidilm

2021-08-09 13:40 UTC, pitkamak approved these changes

2021-08-10 06:59 UTC, pretseli requested changes

2021-08-10 06:59 UTC, pretseli commented on src/main/app/cypress/data/koulutus.ts
> +  return _.merge(getBaseFields({ tyyppi }), {
Vaihdoin aiemmin nähin cypressin filuihin, että käytetään suoraan lodash/fp:stä tuota mergeä ja niitä paria muuta funktiota. On vähän hämmentävää, että tämä ilmeisesti jostain syystä toimii nyt näinkin, vaikka importti puuttuu kokonaan tuolle alaviivalle 😅 .
```suggestion
  return merge(getBaseFields({ tyyppi }), {
```

2021-08-10 06:59 UTC, pretseli commented on src/main/app/cypress/integration/koulutusForm/createKoulutusForm.ts
> +    });
Tämä näyttääkin olevan samankaltainen testi nyt kuin muutkin, joten voit käyttää sitä `mutationTest`-wrapperia. Se tekee tuon intercept-kutsun ja snapshot-vertailun. Voit katsoa mallia muista testeistä.

2021-08-10 06:59 UTC, pretseli commented on src/main/app/cypress/integration/koulutusForm/editKoulutusForm.ts
> +  });
Tässä voi myös käyttää mutationTest-wrapperia.

2021-08-10 06:59 UTC, pretseli commented on src/main/app/src/pages/koulutus/KoulutusForm/KuvausFieldsSection.tsx
> +          required={koulutustyyppi === KOULUTUSTYYPPI.TUVA ? true : false}
```suggestion
          required={koulutustyyppi === KOULUTUSTYYPPI.TUVA}
```

2021-08-10 06:59 UTC, pretseli commented on src/main/app/src/pages/koulutus/KoulutusForm/TiedotSection/TuvaTiedotSection.tsx
> +          required={true}
```suggestion
          required
```

2021-08-10 06:59 UTC, pretseli commented on src/main/app/src/pages/koulutus/KoulutusForm/TiedotSection/TuvaTiedotSection.tsx
> +          disabled={true}
```suggestion
          disabled
```

2021-08-10 06:59 UTC, pretseli commented on src/main/app/src/utils/koulutus/getKoulutusByFormValues.ts
> +        {}
```suggestion
        values?.description?.linkkiEPerusteisiin ?? {}
```

2021-08-10 06:59 UTC, pretseli commented on src/main/app/src/utils/koulutus/koulutusRemoteErrorsToFormErrors.ts
> +    };
Näissä pitäs lisäksi katsoa, että `errorType` täsmää, ettei näytetä noita samoja virheilmoja, jos noihin kenttiin sattuukin tulemaan jokin muu virhe.

2021-08-10 10:12 UTC, pretseli commented on src/main/app/src/pages/koulutus/KoulutusForm/TiedotSection/TiedotSection.tsx
> +              required={true}
```suggestion
              required
```

2021-08-10 10:13 UTC, pretseli approved these changes

2021-08-10 10:42 UTC, heidilm commented on src/main/app/src/pages/koulutus/KoulutusForm/TiedotSection/TiedotSection.tsx
> +              required={true}
Itseasiassa huomasin just että tämän koko hakasulkujen sisällä olevan koodin voi poistaa, koska Tuvalle on oma TuvaTiedotSection. Tää turhaksi jäänyt muutos on vaan jääny siivoamatta pois.

2021-08-10 12:24 UTC, merged