Kto 1335 painotetut arvosanat
Opetushallitus/kouta-ui pull request #344
Opened 2021-09-08 11:11 UTC by heidilm

2021-09-08 11:21 UTC, pitkamak approved these changes

2021-09-10 06:52 UTC, pretseli requested changes

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/utils/hakukohde/getPainotetutOppiaineetOptions.tsx
> +    const kieletInKieliTaso = lukionKielivalikoima[kieliTaso];
```suggestion
_.forEach(lukionKielivalikoima, (kieletInKieliTaso, kieliTaso) => {
```

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/utils/hakukohde/getPainotetutOppiaineetOptions.tsx
> +      const kieliPrefix = kieliTaso.match(/^[A-Z]\d/g); // E.g. A1, B3...
```suggestion
      const kieliPrefix = kieliTaso.match(/^[A-C]\d/g); // E.g. A1, B3...
```

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/utils/hakukohde/getPainotetutOppiaineetOptions.tsx
> +  }
```suggestion
  return kieli ? `${oppiaine}/${kieli}` : `${oppiaine}`;
```

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/pages/hakukohde/HakukohdeForm/PainotetutArvosanatFields.tsx
> +            <Box display="flex" style={{ alignSelf: 'end' }}>
```suggestion
            <Box display="flex" alignSelf="flex-end">
```

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/pages/hakukohde/HakukohdeForm/PainotetutArvosanatFields.tsx
> +    lukionKielivalikoima
Nämä vois mun mielestä kapseloida ihan omaan hookkiinsa `usePainotetutOppiaineetOptions`, jolle annetaan vain tuo lukionKielivalikoima parametrina.

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/pages/hakukohde/HakukohdeForm/PainotetutArvosanatFields.tsx
> +              </Button>
Käytä komponenttia `RemoveButton`

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/pages/hakukohde/HakukohdeForm/PainotetutArvosanatFields.tsx
> +        </Button>
Lisäysnapeille ei näköjään ollut omaa komponenttia, mutta `IconButton` löytyy ja sitä on käytetty muille lisäys-napeille (iconType="add").

2021-09-10 06:52 UTC, pretseli commented on src/main/app/src/utils/hakukohde/hakukohdeRemoteErrorsToFormErrors.ts
> +    }
Eiks tän voi tehdä vaan näin?
```suggestion
    return {
      field: path.replace('metadata.', '').replace('koodiUrit', 'painotettuOppiaine');,
      errorKey: 'validointivirheet.pakollinen',
    }
```

2021-09-13 11:04 UTC, pretseli approved these changes

2021-09-14 08:10 UTC, merged