Kto 1429 suodatus nakyvyydella
Opetushallitus/kouta-ui pull request #405
Opened 2022-03-16 09:03 UTC by heidilm

2022-03-16 09:06 UTC, pitkamak approved these changes

2022-03-16 11:46 UTC, pretseli requested changes

2022-03-16 11:46 UTC, pretseli commented on src/main/app/src/pages/HomePage/utils.ts
> +
Tarviiko tätä edes jos tuo ei ole multi-select?

2022-03-18 07:12 UTC, heidilm commented on src/main/app/src/pages/HomePage/utils.ts
> +
Poistin multi-selectin ja muutin tämän funkkarin nimen `nakyvyysToBoolean`. Tätä tarvitaan siihen, että muutetaan string (`julkinen/ei_julkinen`) booleanille, joka lähetetään HTTP-pyynnössä (`?julkinen=true/false`).

2022-03-18 07:31 UTC, pretseli approved these changes

2022-03-18 07:38 UTC, merged