WIP / first stab: replace draft.js with Lexical
Opetushallitus/kouta-ui pull request #520
Opened 2023-03-24 14:26 UTC by vaeinoe

As draft.js support has ended, replace it with a custom editor based on Lexical sandbox code.

2023-05-26 09:14 UTC, SalamaGofore commented on src/main/app/src/components/LexicalEditorUI/LexicalEditorUI.tsx
> +export default LexicalEditorUI;
Ehkä tämän default exportin voisi jättää pois

2023-05-26 11:55 UTC, SalamaGofore requested changes

2023-05-26 11:55 UTC, SalamaGofore commented on src/main/app/src/components/LexicalEditorUI/ui/DropDown.tsx
> +
Onko tässä muutoksia toiminnallisuuteen?

2023-05-30 11:48 UTC, vaeinoe commented on src/main/app/src/components/LexicalEditorUI/plugins/ToolbarPlugin/Components.tsx
> +
Tässä on tyylitelty sen verran pluginia uusiksi ja wrapattu koko komeus styled-componentsiin, että lisenssiä ei taida kannata lisätä. Tuolta toisaalta kyllä oli tippunut pois.

2023-05-30 12:22 UTC, vaeinoe commented on src/main/app/src/components/LexicalEditorUI/plugins/FloatingLinkEditorPlugin/index.tsx
> +/* eslint-disable no-negated-condition */
Merkitsin olennaiset muutokset headeriin.

2023-05-30 12:24 UTC, vaeinoe commented on src/main/app/src/components/LexicalEditorUI/plugins/ToolbarPlugin/index.tsx
> +
Tarvitsi, oli tippunut pois. Merkitsin myös kommentilla olennaiset muutokset.

2023-05-30 12:25 UTC, vaeinoe commented on src/main/app/src/components/LexicalEditorUI/ui/DropDown.tsx
> +
Tässä oli vain wrapattu tyylit styled-componentsilla ja siistitty + viilattu tyylejä hiukan. Merkitsin tähänkin kommentilla.

2023-06-01 07:20 UTC, SalamaGofore approved these changes

2023-07-11 07:20 UTC, merged