Oy 4340
Opetushallitus/kouta-ui pull request #558
Opened 2023-11-22 08:43 UTC by dmitrymarokhonov

2024-01-10 08:02 UTC, pretseli requested changes
Liittäjäorganisaatioiden komponenteissa ei pitäisi viitata tarjoajiin.

2024-01-10 13:43 UTC, pretseli commented on src/main/app/.env.development
> +DEV_VIRKAILIJA_URL=https://virkailija.untuvaopintopolku.fi
Älä muuta tätä. Käytä .env.development.local tiedostoa, jos haluat itse käyttää lokaalisti jotain.

2024-01-10 13:43 UTC, pretseli commented on src/main/app/src/pages/haku/HakuForm/hakukohteenLiittajaOrganisaatiot/HakukohteenLiittajatWithPagination.tsx
> +            placeholder={t('koulutuslomake.haeJarjestajanNimella')}
Käännösavain pitänee vaihtaa tässä joksikin muuksi, kun ei haeta järjestäjiä...

2024-01-10 13:43 UTC, pretseli commented on src/main/app/src/pages/haku/HakuForm/hakukohteenLiittajaOrganisaatiot/LiittajaOrganisaatiotSection.tsx
> +// import { useFieldValue } from '#/src/hooks/form';
Poista vielä kommentoidut

2024-01-10 13:43 UTC, pretseli commented on src/main/app/src/pages/haku/HakuForm/hakukohteenLiittajaOrganisaatiot/LiittajaOrganisaatiotSection.tsx
> +        organisaatioOid={organisaatioOid}
Jos oikein luin, niin organisaatioOid taitaa olla tässä tarpeeton.
```suggestion
```

2024-01-10 13:58 UTC, dmitrymarokhonov commented on src/main/app/.env.development
> +DEV_VIRKAILIJA_URL=https://virkailija.untuvaopintopolku.fi
joo, se on mennyt vahingossa komittiin

2024-01-11 07:28 UTC, pretseli approved these changes

2024-02-23 14:36 UTC, merged